//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kursovayaKuznetsova
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ChainModelContainer : DbContext
    {
        public ChainModelContainer()
            : base("name=ChainModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Chain> ChainSet { get; set; }
        public virtual DbSet<Stock> StockSet { get; set; }
        public virtual DbSet<Product> ProductSet { get; set; }
        public virtual DbSet<Manufactor> ManufactorSet { get; set; }
        public virtual DbSet<Store> StoreSet { get; set; }
        public virtual DbSet<Shift> ShiftSet { get; set; }
        public virtual DbSet<Check> CheckSet { get; set; }
        public virtual DbSet<CheckUnit> CheckUnitSet { get; set; }
        public virtual DbSet<CheckDiscount> CheckDiscountSet { get; set; }
        public virtual DbSet<Seller> SellerSet { get; set; }
        public virtual DbSet<ProductDiscount> ProductDiscountSet { get; set; }
        public virtual DbSet<ProductType> ProductTypeSet { get; set; }
        public virtual DbSet<Request> RequestSet { get; set; }
        public virtual DbSet<RequestProduct> RequestProductSet { get; set; }
    }
}
