//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kursovayaKuznetsova
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDiscount
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public int Value { get; set; }
        public Nullable<int> ComboId { get; set; }
        public Nullable<int> FromNum { get; set; }
        public string FromNumCombo { get; set; }
    
        public virtual ProductType ProductType { get; set; }
    }
}
