//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kursovayaKuznetsova
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public int StockId { get; set; }
        public int Amount { get; set; }
        public int ProductTypeId { get; set; }
        public bool IsParfume { get; set; }
    
        public virtual Stock Stock { get; set; }
        public virtual ProductType ProductType { get; set; }
    }
}
