//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kursovayaKuznetsova
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestProduct
    {
        public int Id { get; set; }
        public string ProductTypeId { get; set; }
        public string ManufactorId { get; set; }
        public string Amount { get; set; }
        public int RequestId { get; set; }
        public int RequestId1 { get; set; }
    
        public virtual Request Request { get; set; }
    }
}
